Feature/rf07 cadastro de usuarios
LuminaCritics/LuminaCritics pull request #15
Opened 2023-09-27 15:17 UTC by luccasocastro

2023-09-27 20:12 UTC, MDyeimison requested changes
Por favor realize as mudanças solicitadas nos comentários, no geral está muito bom :+1:

2023-09-27 20:12 UTC, MDyeimison commented on backend/critics/views.py
> +class UsuarioCreateView(APIView):
remover a requisição de estar autenticado [IsAuthenticated] ao criar o usuário

2023-09-27 20:12 UTC, MDyeimison commented on backend/critics/models.py
> +    senha = models.CharField(max_length=128)
adicionar criptografia de senha, não salvar diretamente no banco de dados

2023-09-27 20:12 UTC, MDyeimison commented on backend/luminacritics/settings.py
> +    'rest_framework',
adicionar ou atualizar arquivo requirements.txt com os pacotes utilizados

2023-09-27 23:21 UTC, luccasocastro commented on backend/critics/views.py
> +class UsuarioCreateView(APIView):
removido!

2023-09-27 23:22 UTC, luccasocastro commented on backend/critics/models.py
> +    senha = models.CharField(max_length=128)
foi adicionada a criptografia!

2023-09-27 23:23 UTC, luccasocastro commented on backend/luminacritics/settings.py
> +    'rest_framework',
feito!

2023-09-27 23:24 UTC, luccasocastro commented
Mudanças concluídas! Favor reavaliar

2023-09-28 04:54 UTC, MDyeimison commented
Favor resolver os conflitos. No mais tudo certo :+1:

2023-09-28 12:32 UTC, luccasocastro commented
Conflitos resolvidos!

2023-09-28 12:32 UTC, merged